# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e436aa9d2f756034a14d3c5341e5d001e68fe18ca0f38084844b85a529d5cba05fbfc917fe7827dac9dfa2c73e19f8c174b4db8df703ae313798689d8d21503

test:
  secret_key_base: e4d662f964f46609d2abacea8a41dae2b260f55b669e7ccfcd1fe994f65bdc7c083d87930b94cc0cf4b0c04b83650907bb264279d8e20f243d8cf443a6337120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
